e1=Environment(COMPILATIONDB_USE_ABSPATH=True,CCFLAGS='-g -Wall')
e1.ParseConfig('pkg-config --cflags --libs sdl2')
e1.Tool('compilation_db')
e1.CompilationDatabase()
e1.Program('yt',Glob('3.cpp'))
e2=Environment(COMPILATIONDB_USE_ABSPATH=True)
e2.Tool('compilation_db')
e2.CompilationDatabase()
e2.Program('mr','8.cpp')
